name: outfits
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.17.0
  cloud_firestore: ^4.7.0
  google_fonts: ^6.1.0
  video_player: ^2.7.0
  video_player_web: ^2.0.17
  font_awesome_flutter: ^10.5.0
  google_sign_in: ^5.4.2
  image_picker: ^1.0.7
  image: ^4.0.17
  transparent_image: ^2.0.0
  http: ^1.1.0  # Actualizado a la versión más reciente compatible
  http_parser: ^4.0.2
  animated_splash_screen: ^1.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  uuid: ^4.2.2
  flutter_dotenv: ^5.0.2      
  cloudinary_flutter: ^1.3.0
  cloudinary_url_gen: ^1.7.0

  
  
  


 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/home.mp4
    - assets/google.png
    - assets/logo.png
    - assets/fondo.jpg
    - assets/ROPA/1.png
    - assets/ROPA/2.png
    - assets/ROPA/3.png
    - assets/ROPA/4.png
    - assets/ROPA/5.png
    - assets/ROPA/6.png
    - .env